spring.application.name=interview-scheduler-system
spring.main.banner-mode=off

# Logging
logging.level.root=WARN
logging.level.com.company.iss=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.com.vaadin=WARN
logging.level.org.atmosphere=WARN
logging.level.com.zaxxer.hikari=WARN

# MySQL datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Session
server.servlet.session.timeout=30m
