CREATE TABLE booking_lifecycle_history (
    action VARCHAR(40) NOT NULL,
    appointment_date DATE NOT NULL,
    end_time TIME(0) NOT NULL,
    actor_id BIGINT NOT NULL,
    booking_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    occurred_at TIMESTAMP(6) NOT NULL,
    schedule_id BIGINT NOT NULL,
    start_time TIME(0) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT,
    booking_reference VARCHAR(50) NOT NULL,
    branch_display_name VARCHAR(255),
    recruiter_display_name VARCHAR(255),
    interview_mode ENUM ('ONLINE','ONSITE','PHONE') NOT NULL,
    interview_stage ENUM ('CLIENT','FINAL','INITIAL') NOT NULL,
    new_status VARCHAR(30) NOT NULL,
    previous_status VARCHAR(30),
    PRIMARY KEY (id),
    CONSTRAINT uk_booking_lifecycle_action UNIQUE (booking_id, action),
    CONSTRAINT chk_booking_lifecycle_transition CHECK (
        CASE action
            WHEN 'BOOKING_CREATED' THEN
                previous_status IS NULL AND new_status = 'BOOKED'
            WHEN 'BOOKING_CONFIRMED' THEN
                previous_status IS NOT NULL
                    AND previous_status = 'BOOKED'
                    AND new_status = 'CONFIRMED'
            WHEN 'ATTENDANCE_RECORDED' THEN
                previous_status IS NOT NULL
                    AND previous_status = 'CONFIRMED'
                    AND new_status = 'ATTENDED'
            WHEN 'NO_SHOW_RECORDED' THEN
                previous_status IS NOT NULL
                    AND previous_status = 'CONFIRMED'
                    AND new_status = 'NO_SHOW'
            WHEN 'BOOKING_CANCELLED' THEN
                CASE previous_status
                    WHEN 'BOOKED' THEN new_status = 'CANCELLED'
                    WHEN 'CONFIRMED' THEN new_status = 'CANCELLED'
                    ELSE FALSE
                END
            ELSE FALSE
        END
    ),
    CONSTRAINT fk_booking_lifecycle_actor FOREIGN KEY (actor_id) REFERENCES users (id),
    CONSTRAINT fk_booking_lifecycle_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT fk_booking_lifecycle_schedule FOREIGN KEY (schedule_id) REFERENCES schedules (id)
);

CREATE INDEX idx_booking_lifecycle_timeline
    ON booking_lifecycle_history (booking_id, occurred_at, id);

ALTER TABLE booking_reschedule_history ADD COLUMN snapshot_version SMALLINT NULL;
ALTER TABLE booking_reschedule_history ADD COLUMN source_appointment_date DATE NULL;
ALTER TABLE booking_reschedule_history ADD COLUMN source_start_time TIME(0) NULL;
ALTER TABLE booking_reschedule_history ADD COLUMN source_end_time TIME(0) NULL;
ALTER TABLE booking_reschedule_history ADD COLUMN source_interview_mode ENUM ('ONLINE','ONSITE','PHONE') NULL;
ALTER TABLE booking_reschedule_history ADD COLUMN source_recruiter_display_name VARCHAR(255) NULL;
ALTER TABLE booking_reschedule_history ADD COLUMN source_branch_display_name VARCHAR(255) NULL;
ALTER TABLE booking_reschedule_history ADD COLUMN destination_appointment_date DATE NULL;
ALTER TABLE booking_reschedule_history ADD COLUMN destination_start_time TIME(0) NULL;
ALTER TABLE booking_reschedule_history ADD COLUMN destination_end_time TIME(0) NULL;
ALTER TABLE booking_reschedule_history ADD COLUMN destination_interview_mode ENUM ('ONLINE','ONSITE','PHONE') NULL;
ALTER TABLE booking_reschedule_history ADD COLUMN destination_recruiter_display_name VARCHAR(255) NULL;
ALTER TABLE booking_reschedule_history ADD COLUMN destination_branch_display_name VARCHAR(255) NULL;
